import type { Metadata } from "next";
import { Providers } from "./providers/providers";

import "./globals.css";
import Header from "./components/header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

        <Providers>
          <Header />
          {children}
        </Providers>
        
        </body>
    </html>
  );
}
